### ISSUE TITLE
Get the response 'Bad Gateway' when using latest code of luci

### ISSUE THREAD

**Issue by garywangcn** [jow-/lucihttp#1]
I also reported this issue to here: https://github.com/openwrt/luci/issues/1784.

After investigating this problem, I found the lua script(http.lua) calls header_attribute to parse header attribute, but never get return, so uhttpd gives the response 'Bad Gateway' to web client.

Below is the call trace I found, can you please help me to fix this problem?

> http.lua: parse_message_body
>    -> lua.c: lhttp.header_attribute
>            -> ulits.c: lh_header_attribute (hang in this function)
>

**Comment by jow-** [comment]
Can you find out which input is causing the hang?

**Comment by cdbierl** [comment]
Yeah I have the same behavior. How can I confirm the same call trace? I see nothing in the logs.

**Comment by jow-** [comment]
@garywangcn - can you provide me with any test case or sample input triggering the problem?

**Comment by garywangcn** [comment]
@jow- 
I just use the latest luci package from here https://github.com/openwrt/luci, no special setting for it.
And when I access https://192.168.1.1/cgi-bin/luci, I will get the response "Bad Gateway".

If I add “return 0;" before calling lh_header_attribute in function lh_L_header_attribute(lucihttp-2018-04-22-ccc685e5/lib/lua.c), I'll get a response, even though it's incorrect.

```
static int
lh_L_header_attribute(lua_State *L)
{
        size_t len;
        char *value;
        const char *hval = luaL_optlstring(L, 1, NULL, &len);
        const char *attr = luaL_optstring(L, 2, NULL);

        if (!hval)
                return 0;

        return 0;   // Debug code

        value = lh_header_attribute(hval, len, attr, &len);

```

**Comment by jow-** [comment]
This does not help unfortunately. Can you add something like `fprintf(stderr, "hval=[%s] attr=[%s]\n", hval ? hval : "-", attr ? attr : "-");` instead of the return and check `logread` when you encounter the problem?

**Comment by garywangcn** [comment]
@jow- 
After investigating this issue, I have the following clue
I add the following debug code, and get below output:

Debug code:
> fprintf(file, "hval=[%s] attr=[%s]\n", hval ? hval : "-", attr ? attr : "-");

Log in file:

> hval=[] attr=[-]

So looks like the pointer hval is not NULL, but the size of string is zero.
After I applied the below code，the issue disappears, can you please review below changes. I'm not familiar the code of this library, so not sure if the change can fix this problem totally.

> static int
> lh_L_header_attribute(lua_State *L)
> {
>       ......
>       if (!hval || (strlen(hval) == 0) )
>             return 0;

**Comment by jow-** [comment]
@garywangcn - thanks a lot for your feedback. I was testing all kinds of random garbage but never the empty string :)

**Comment by garywangcn** [comment]
@jow- I have no idea why this happens, but this issue was reported many times by a few developers.

**Comment by rufengsuixing** [comment]
model/cbi/usb3disable.lua
`local sys=require("luci.sys")
local m,s,e
m=Map("usb3disable","usb3disable")

s=m:section(TypedSection,"usb3disable")
s.anonymous=true
s.addremove=false

e=s:option(Button,"disabled",translate("disable now"))
e.optional=false
e.inputtitle=translate("Disable")
e.write=function()
	sys.exec("cat /etc/modules.d/$(ls /etc/modules.d | grep usb3) | sed -n '1!G;h;$p' | xargs rmmod")
	luci.http.redirect(luci.dispatcher.build_url("admin","system","usb3disable"))
end

return m`
can use 
but
`local sys=require("luci.sys")
local m,s,e
m=Map("usb3disable","usb3disable")

s=m:section(TypedSection,"usb3disable")
s.anonymous=true
s.addremove=false

e=s:option(Button,"disabled",translate("disable now"))
e.optional=false
e.inputtitle=translate("Disable")
e.write=function()
	sys.exec("cat /etc/modules.d/$(ls /etc/modules.d | grep usb3) | sed -n '1!G;h;$p' | xargs rmmod")
	luci.http.redirect(luci.dispatcher.build_url("admin","system","usb3disable"))
end
if sys.call("ls /etc/modules-boot.d | grep usb3")==0 then
	e=s:option(Button,"disabledstartup",translate("disable on boot"))
	e.optional=false
	e.inputtitle=translate("Disable")
	e.write=function()
		sys.exec("rm /etc/modules-boot.d/*-usb3")
		luci.http.redirect(luci.dispatcher.build_url("admin","system","usb3disable"))
	end
else
	e=s:option(Button,"enabledstartup",translate("enable on boot"))
	e.optional=false
	e.inputtitle=translate("Enable")
	e.write=function()
		sys.exec("ln -s /etc/modules.d/*usb3 /etc/modules-boot.d/")
		luci.http.redirect(luci.dispatcher.build_url("admin","system","usb3disable"))
	end
end
return m`
will show bad gateway
